# @format

BOT:
  OWNERS: ["1155913063921373224"]
  ADMINS: ["721011468929073213"]
  MODERATORS: ["1155913063921373224"]
  STAFF: ["1155913063921373224"]

LINKS:
  SUPPORT: "https://discord.gg/dhominojdc"
  MONGO_URI: "mongodb+srv://angel:angel@cluster0.c9ouu1k.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  PATREON: "https://www.patreon.com/"
  VOTING: "https://top.gg/bot/"
  HOSTING: "https://client.elixior.cloud?ref=JUPIVERSE"
  HOSTINGSUPPORT: "https://discord.gg/etteU4zcuw"

SPOTIFY:
  ID: "e7c9c292bbc24745b33743348e560d96"
  SECRET: "4726d6d6eba34cfe889c26844fcabc97"

MANAGER:
  OWNERS: ["1155913063921373224"]
  TOKEN: ""

FELINE:
  PREFIX: "="
  EMOJIS: "black"
  COLOR: "#555555"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: ""
  TOPGGAUTH: ""

JINGLE:
  PREFIX: "?"
  EMOJIS: "black"
  COLOR: "#555555"
  SHARDS: "auto"
  PER_CLUSTER: 2
  TOKEN: "" #"MTI0MjQyODg2MjM1NzU3Mzc1Mw.G6aWL5.35mA1e_UtEIHF7oJIcCtnKkTJNehjBOLSjewKs"
  TOPGGAUTH: ""
  VOTEURI: ""
  
KYOKO:
  PREFIX: "&"
  EMOJIS: "black"
  COLOR: "#551155"
  SHARDS: "auto"
  PER_CLUSTER: 2
  TOKEN: "" #"MTI0MjQyODg2MjM1NzU3Mzc1Mw.G6aWL5.35mA1e_UtEIHF7oJIcCtnKkTJNehjBOLSjewKs"
  TOPGGAUTH: ""

WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1271898959966769182/JPfNdPOhpBA0MmTmnOTOpNeA-vMoD96Vo5ZRWPqdEIeZYb_wbYbC4bsoIXYjOFlWnpU_"
  STATIC: "https://discord.com/api/webhooks/1271898959966769182/JPfNdPOhpBA0MmTmnOTOpNeA-vMoD96Vo5ZRWPqdEIeZYb_wbYbC4bsoIXYjOFlWnpU_"
  PLAYER: "https://discord.com/api/webhooks/1271898959966769182/JPfNdPOhpBA0MmTmnOTOpNeA-vMoD96Vo5ZRWPqdEIeZYb_wbYbC4bsoIXYjOFlWnpU_"
  SERVER: "https://discord.com/api/webhooks/1271898959966769182/JPfNdPOhpBA0MmTmnOTOpNeA-vMoD96Vo5ZRWPqdEIeZYb_wbYbC4bsoIXYjOFlWnpU_"
  COMMAND: "https://discord.com/api/webhooks/1271898959966769182/JPfNdPOhpBA0MmTmnOTOpNeA-vMoD96Vo5ZRWPqdEIeZYb_wbYbC4bsoIXYjOFlWnpU_"
